export const official23Products = [
  {
    name: 'AC wire 4MM HPL',
    sku: 'APL-ACW-4H',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 5500,
    inStock: true,
  },
  {
    name: 'AC wire 4MM Polycab',
    sku: 'APL-ACW-4P',
    category: 'Wires & Cables',
    unit: 'per mtr',
    gstPercent: 18,
    baseRate: 62,
    inStock: true,
  },
  {
    name: 'AC wire 6MM HPL',
    sku: 'APL-ACW-6H',
    category: 'Wires & Cables',
    unit: 'per mtr',
    gstPercent: 18,
    baseRate: 81,
    inStock: true,
  },
  {
    name: 'AC wire 6MM Polycab',
    sku: 'APL-ACW-6P',
    category: 'Wires & Cables',
    unit: 'per mtr',
    gstPercent: 18,
    baseRate: 81,
    inStock: true,
  },
  {
    name: 'ACDB + DCBB combo 1 Phas',
    sku: 'APL-DB-1PH',
    category: 'Electrical Panels',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1850,
    inStock: true,
  },
  {
    name: 'Base plate 80x40',
    sku: 'APL-BP-8040',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 130,
    inStock: true,
  },
  {
    name: 'Base plate 140x50',
    sku: 'APL-BP-14050',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 198,
    inStock: true,
  },
  {
    name: 'DC wire 4MM HPL',
    sku: 'APL-DCW-4H',
    category: 'Wires & Cables',
    unit: 'per mtr',
    gstPercent: 18,
    baseRate: 51,
    inStock: true,
  },
  {
    name: 'DC wire 4MM Polycab',
    sku: 'APL-DCW-4P',
    category: 'Wires & Cables',
    unit: 'per mtr',
    gstPercent: 18,
    baseRate: 57,
    inStock: true,
  },
  {
    name: 'Earthing rod 1 mtr.',
    sku: 'APL-ER-1M',
    category: 'Earthing & Lightning',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 300,
    inStock: true,
  },
  {
    name: 'Earthing rod 2 mtr.',
    sku: 'APL-ER-2M',
    category: 'Earthing & Lightning',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 400,
    inStock: true,
  },
  {
    name: 'Earthing wire 10m ALU',
    sku: 'APL-EW-10A',
    category: 'Wires & Cables',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1450,
    inStock: true,
  },
  {
    name: 'Earthing wire 16mm ALU',
    sku: 'APL-EW-16A',
    category: 'Wires & Cables',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 2250,
    inStock: true,
  },
  {
    name: 'Earthing wire 6mm CCA',
    sku: 'APL-EW-6C',
    category: 'Wires & Cables',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1850,
    inStock: true,
  },
  {
    name: 'End Clamp',
    sku: 'APL-EC-001',
    category: 'Clamps & Joiners',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 35,
    inStock: true,
  },
  {
    name: 'Lightning Arrestor',
    sku: 'APL-LA-001',
    category: 'Earthing & Lightning',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 400,
    inStock: true,
  },
  {
    name: 'MC4 connector',
    sku: 'APL-MC4-001',
    category: 'Accessories',
    unit: 'per pair',
    gstPercent: 18,
    baseRate: 50,
    inStock: true,
  },
  {
    name: 'Mid clamp',
    sku: 'APL-MC-001',
    category: 'Clamps & Joiners',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 45,
    inStock: true,
  },
  {
    name: 'Nut bolt washer',
    sku: 'APL-NBW-001',
    category: 'Fasteners & Hardware',
    unit: 'per kg',
    gstPercent: 18,
    baseRate: 120,
    inStock: true,
  },
  {
    name: 'Purlin 21ft 41x41',
    sku: 'APL-PUR-2141',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1150,
    inStock: true,
  },
  {
    name: 'Pit Cover',
    sku: 'APL-PIT-001',
    category: 'Accessories',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 149,
    inStock: true,
  },
  {
    name: 'Rafter 21ft 140x50',
    sku: 'APL-RAF-21140',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 2251,
    inStock: true,
  },
  {
    name: 'Rafter 21ft 80x40',
    sku: 'APL-RAF-2180',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1390,
    inStock: true,
  },
];
