import re

content = """export const official23Products = [
  {
    name: 'AC WIRE 4MM HPL',
    sku: 'APL-ACW-4H',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 5500,
    inStock: true,
  },
  {
    name: 'AC WIRE 4MM POLYCAB',
    sku: 'APL-ACW-4P',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 6200,
    inStock: true,
  },
  {
    name: 'AC WIRE 6MM HPL',
    sku: 'APL-ACW-6H',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 8100,
    inStock: true,
  },
  {
    name: 'AC WIRE 6MM POLYCAB',
    sku: 'APL-ACW-6P',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 8100,
    inStock: true,
  },
  {
    name: 'DC WIRE 4MM HPL',
    sku: 'APL-DCW-4H',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 5100,
    inStock: true,
  },
  {
    name: 'DC WIRE 4MM POLYCAB',
    sku: 'APL-DCW-4P',
    category: 'Wires & Cables',
    unit: 'Coil',
    gstPercent: 18,
    baseRate: 5700,
    inStock: true,
  },
  {
    name: 'ACDB+DCDB COMBO',
    sku: 'APL-DB-1PH',
    category: 'Electrical Panels',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1850,
    inStock: true,
  },
  {
    name: 'BASE PLATE 80X40',
    sku: 'APL-BP-8040',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 130,
    inStock: true,
  },
  {
    name: 'BASE PLATE 140X50',
    sku: 'APL-BP-14050',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 198,
    inStock: true,
  },
  {
    name: 'EARTHING ROD 1MTR.',
    sku: 'APL-ER-1M',
    category: 'Earthing & Lightning',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 300,
    inStock: true,
  },
  {
    name: 'EARTHING ROD 2MTR.',
    sku: 'APL-ER-2M',
    category: 'Earthing & Lightning',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 400,
    inStock: true,
  },
  {
    name: 'EARTHING WIRE 10MM ALU',
    sku: 'APL-EW-10A',
    category: 'Wires & Cables',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1450,
    inStock: true,
  },
  {
    name: 'EARTHING WIRE 16MM ALU',
    sku: 'APL-EW-16A',
    category: 'Wires & Cables',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 2250,
    inStock: true,
  },
  {
    name: 'EARTHING WIRE 6MM CCA',
    sku: 'APL-EW-6C',
    category: 'Wires & Cables',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1850,
    inStock: true,
  },
  {
    name: 'END CLAMP',
    sku: 'APL-EC-001',
    category: 'Clamps & Joiners',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 35,
    inStock: true,
  },
  {
    name: 'MID CLAMP',
    sku: 'APL-MC-001',
    category: 'Clamps & Joiners',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 45,
    inStock: true,
  },
  {
    name: 'LIGHTNING ARRESTOR',
    sku: 'APL-LA-001',
    category: 'Earthing & Lightning',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 400,
    inStock: true,
  },
  {
    name: 'MC4 CONNECTOR',
    sku: 'APL-MC4-001',
    category: 'Accessories',
    unit: 'per pair',
    gstPercent: 18,
    baseRate: 50,
    inStock: true,
  },
  {
    name: 'NUT BOLT WASHER',
    sku: 'APL-NBW-001',
    category: 'Fasteners & Hardware',
    unit: 'per kg',
    gstPercent: 18,
    baseRate: 120,
    inStock: true,
  },
  {
    name: 'STRUT CHANEEL 41X41',
    sku: 'APL-PUR-2141',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1150,
    inStock: true,
  },
  {
    name: 'C CHANNEL 21FT 140X50',
    sku: 'APL-RAF-21140',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 2251,
    inStock: true,
  },
  {
    name: 'C CHANNEL 21FT 80X40',
    sku: 'APL-RAF-2180',
    category: 'G.I. Solar Mounting Structure',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 1480,
    inStock: true,
  },
  {
    name: 'PIT COVER',
    sku: 'APL-PIT-001',
    category: 'Accessories',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 149,
    inStock: true,
  },
  {
    name: 'FASTNER 6MM',
    sku: 'APL-FST-006',
    category: 'Fasteners & Hardware',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 10,
    inStock: true,
  },
  {
    name: 'FASTNER 10MM',
    sku: 'APL-FST-010',
    category: 'Fasteners & Hardware',
    unit: 'piece',
    gstPercent: 18,
    baseRate: 15,
    inStock: true,
  },
];
"""

with open('src/lib/products.ts', 'w') as f:
    f.write(content)
