import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const defaultProducts = [
  {
    name: 'AC Wire 4MM HPL',
    description: 'HPL 4 sq mm Copper AC Cable (Rate per meter)',
    sku: 'APL-ACW-4H',
    category: 'Wires & Cables',
    unit: 'Mtr',
    gstPercent: 18,
    baseRate: 55,
    inStock: true,
  },
  {
    name: 'AC Wire 4MM Polycab',
    description: 'Polycab 4 sq mm Copper AC Cable (Rate per meter)',
    sku: 'APL-ACW-4P',
    category: 'Wires & Cables',
    unit: 'Mtr',
    gstPercent: 18,
    baseRate: 62,
    inStock: true,
  },
  {
    name: 'AC Wire 6MM HPL',
    description: 'HPL 6 sq mm Copper AC Cable (Rate per meter)',
    sku: 'APL-ACW-6H',
    category: 'Wires & Cables',
    unit: 'Mtr',
    gstPercent: 18,
    baseRate: 81,
    inStock: true,
  },
  {
    name: 'AC WIRE 6MM POLYCAB',
    description: 'Polycab 6 sq mm Copper AC Cable',
    sku: 'APL-ACW-6P',
    category: 'Wires & Cables',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 81,
    inStock: true,
  },
  {
    name: 'ACDB 1PH',
    description: 'Single Phase AC Distribution Box with MCB & SPD',
    sku: 'APL-ACDB-1PH',
    category: 'Electrical Panels',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'ACDB 3PH',
    description: 'Three Phase AC Distribution Box with 4P MCB/MCCB & Class II SPD',
    sku: 'APL-ACDB-3PH',
    category: 'Electrical Panels',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Base Plate 140X50',
    description: 'Heavy Duty Base Plate for 140x50 column mounting',
    sku: 'APL-BP-14050',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 190,
    inStock: true,
  },
  {
    name: 'Base Plate 80X40',
    description: 'Base Plate for 80x40 column/leg mounting',
    sku: 'APL-BP-8040',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 190,
    inStock: true,
  },
  {
    name: 'DC Wire 4MM HPL (100Mtr)',
    description: 'HPL 4 sq mm Tinned Copper Solar DC Cable (100 Meter Bundle)',
    sku: 'APL-DCW-4H',
    category: 'Wires & Cables',
    unit: 'BDL',
    gstPercent: 18,
    baseRate: 51,
    inStock: true,
  },
  {
    name: 'DC Wire 4MM Polycab (100Mtr)',
    description: 'Polycab 4 sq mm Cross-Linked Solar DC Cable (100 Meter Bundle)',
    sku: 'APL-DCW-4P',
    category: 'Wires & Cables',
    unit: 'BDL',
    gstPercent: 18,
    baseRate: 55,
    inStock: true,
  },
  {
    name: 'DCDB 1 IN 1 OUT',
    description: '1 String In 1 String Out DC Distribution Box (1000V DC SPD + Fuse)',
    sku: 'APL-DCDB-1I1O',
    category: 'Electrical Panels',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'DCDB 2 IN 1 OUT',
    description: '2 String In 1 Out Combined DC Distribution Box',
    sku: 'APL-DCDB-2I1O',
    category: 'Electrical Panels',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'DCDB 2 IN 2 OUT',
    description: 'Dual Tracker 2 In 2 Out DC Distribution Box',
    sku: 'APL-DCDB-2I2O',
    category: 'Electrical Panels',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'DCDB 3 IN 1 OUT',
    description: '3 String In 1 Out DC Distribution Box for multi-MPPT',
    sku: 'APL-DCDB-3I1O',
    category: 'Electrical Panels',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Degree Hanger',
    description: 'Tilt angle adjustment degree hanger bracket',
    sku: 'APL-DH-001',
    category: 'Clamps & Joiners',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Earthing Rod 1mtr',
    description: '1 Meter Copper Bonded / GI Chemical Earthing Electrode',
    sku: 'APL-ER-1M',
    category: 'Earthing & Lightning',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 179,
    inStock: true,
  },
  {
    name: 'Earthing Rod 2mtr',
    description: '2 Meter Copper Bonded / GI Heavy Chemical Earthing Electrode',
    sku: 'APL-ER-2M',
    category: 'Earthing & Lightning',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 299,
    inStock: true,
  },
  {
    name: 'Earthing Wire 10MM ALU',
    description: '10 sq mm Aluminum Earthing Conductor Wire',
    sku: 'APL-EW-10A',
    category: 'Wires & Cables',
    unit: 'Mtr',
    gstPercent: 18,
    baseRate: 1350,
    inStock: true,
  },
  {
    name: 'Earthing Wire 16MM ALU',
    description: '16 sq mm Heavy Aluminum Earthing Conductor Wire',
    sku: 'APL-EW-16A',
    category: 'Wires & Cables',
    unit: 'Mtr',
    gstPercent: 18,
    baseRate: 1950,
    inStock: true,
  },
  {
    name: 'Earthing Wire 6MM CCA',
    description: '6 sq mm Copper Clad Aluminum (CCA) Earthing Wire',
    sku: 'APL-EW-6C',
    category: 'Wires & Cables',
    unit: 'Mtr',
    gstPercent: 18,
    baseRate: 1650,
    inStock: true,
  },
  {
    name: 'End Clamp',
    description: 'Aluminum/GI End Clamp for solar array edges',
    sku: 'APL-EC-001',
    category: 'Clamps & Joiners',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 25,
    inStock: true,
  },
  {
    name: 'L.A. Metal Base',
    description: 'Heavy Metal Base Bracket for Lightning Arrestor Mast',
    sku: 'APL-LAB-MTL',
    category: 'Earthing & Lightning',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'L.A. PVC Base',
    description: 'Insulating PVC Mounting Base for Lightning Arrestor',
    sku: 'APL-LAB-PVC',
    category: 'Earthing & Lightning',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'L.A. Red Insulator Base',
    description: 'High Voltage Red Resin Insulator Base for L.A.',
    sku: 'APL-LAB-RED',
    category: 'Earthing & Lightning',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Lightning Arrestor',
    description: 'ESE / Multi-Spike Copper Lightning Arrestor Spike',
    sku: 'APL-LA-001',
    category: 'Earthing & Lightning',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'MC-4 Connector',
    description: 'IP68 1500V Male & Female Solar MC4 Connectors',
    sku: 'APL-MC4-001',
    category: 'Accessories',
    unit: 'Pair',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Mid Clamp',
    description: 'Aluminum/GI Mid Clamp for solar module framing',
    sku: 'APL-MC-001',
    category: 'Clamps & Joiners',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 25,
    inStock: true,
  },
  {
    name: 'Nut Bolt Washer',
    description: 'SS304/GI Grade 8.8 Nut, Bolt & Spring Washer Set',
    sku: 'APL-NBW-001',
    category: 'Fasteners & Hardware',
    unit: 'KG',
    gstPercent: 18,
    baseRate: 120,
    inStock: true,
  },
  {
    name: 'Pit Cover',
    description: 'Heavy Duty Plastic/FRP Earth Pit Chamber Cover',
    sku: 'APL-PIT-001',
    category: 'Accessories',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 142,
    inStock: true,
  },
  {
    name: 'Purlin 12ft 41X41',
    description: '12ft 41x41mm C-Channel Solar Mounting Purlin',
    sku: 'APL-PUR-1241',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Purlin 21ft 41X41',
    description: '21ft 41x41mm C-Channel Solar Mounting Purlin',
    sku: 'APL-PUR-2141',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Purlin Jointer',
    description: 'Internal/External Purlin connector for continuous run',
    sku: 'APL-PJ-001',
    category: 'Clamps & Joiners',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Rafter 12ft 80X40',
    description: '12ft 80x40mm Structure Rafter Section',
    sku: 'APL-RAF-1280',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Rafter 21ft 140X50',
    description: '21ft 140x50mm Heavy Duty Structure Rafter',
    sku: 'APL-RAF-21140',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Rafter 21ft 80X40',
    description: '21ft 80x40mm Hot Dip Pre-Galvanised Structure Rafter',
    sku: 'APL-RAF-2180',
    category: 'G.I. Solar Mounting Structure',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Rafter Jointer',
    description: 'Heavy Duty Rafter splice connector',
    sku: 'APL-RJ-001',
    category: 'Clamps & Joiners',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  },
  {
    name: 'Solgrip Universal Clamp',
    description: 'Universal Solgrip Module Clamp with grounding teeth',
    sku: 'APL-SUC-001',
    category: 'Clamps & Joiners',
    unit: 'Pcs',
    gstPercent: 18,
    baseRate: 1,
    inStock: true,
  }
];

async function main() {
  let org = await prisma.organization.findFirst({
    where: { name: 'Arpit Solar & Electricals' }
  });

  if (!org) {
    org = await prisma.organization.create({
      data: {
        name: 'Arpit Solar & Electricals'
      }
    });
  }

  // Upsert all 37 products
  for (const product of defaultProducts) {
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: {
        name: product.name,
        description: product.description,
        category: product.category,
        unit: product.unit,
        gstPercent: product.gstPercent,
        baseRate: product.baseRate,
        inStock: product.inStock,
      },
      create: product,
    });
  }

  console.log(`Seeded ${defaultProducts.length} official solar products with exact names, descriptions, and rates!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
